name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.12.0
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm migrate:apply:test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
      - run: pnpm migrate:apply:production
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PRODUCTION }}
