name: CD
on:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  migration-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.12.0
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm migrate:apply:test
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_TEST }}
  migration-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.12.0
      - run: npm install -g pnpm
      - run: pnpm install
      - run: pnpm migrate:apply:production
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL_PRODUCTION }}
  publish-migration-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18.12.0
      - run: npm install -g pnpm
      - run: pnpm install
      - run: |
          echo ${{ secrets.PAT }} | docker login ghcr.io --username ${{ vars.PROJECT_GROUP}} --password-stdin
          docker buildx create --name multi-arch --bootstrap --use
          docker buildx build --push --platform linux/arm64,linux/amd64 --tag ghcr.io/${{ vars.PROJECT_GROUP}}/${{ vars.PROJECT_NAME}}-migration:latest .
